version: '3'

services:
  postgres:
    image: postgres
    shm_size: '2gb'
    container_name: todoapp-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
