###
GET http://localhost:8080/todo

###
GET http://localhost:8080/todo/1

###
POST http://localhost:8080/todo
Content-Type: application/json

{
  "name": "New Todo1"
}

###
DELETE http://localhost:8080/todo/4
