package com.example.todoappspring.commands;

/**
 * The AddTaskToListCommand class is a Command object for the operation of adding a task to a to-do list.
 * A Command object is an object that encapsulates all the information needed to perform an action or trigger an event at a later time. This information includes the method name, the object that owns the method and values for the method parameters.
 * In the context of this application, the AddTaskToListCommand class encapsulates the information needed to add a task to a to-do list, which includes the id of the to-do list and the name of the task.
 * This class is a record, which is a special kind of class in Java that is used to model immutable data. Records automatically have a constructor, equals, hashCode, and toString methods generated by the compiler.
 */
public record AddTaskToListCommand(Long id, String name) {
}
