package com.example.todoappspring.commands;

/**
 * The MarkTaskAsDoneCommand class is a Command object for the operation of marking a task as done.
 * A Command object is an object that encapsulates all the information needed to perform an action or trigger an event at a later time. This information includes the method name, the object that owns the method and values for the method parameters.
 * In the context of this application, the MarkTaskAsDoneCommand class encapsulates the information needed to mark a task as done, which includes the id of the task.
 * This class is a record, which is a special kind of class in Java that is used to model immutable data. Records automatically have a constructor, equals, hashCode, and toString methods generated by the compiler.
 */
public record MarkTaskAsDoneCommand(Long id) {
}
